### ISSUE TITLE
stop using global SERVER_IP and make url a class object

### ISSUE THREAD

**Issue by jgsdavies** [ansys/pymotorcad#135]
![image](https://github.com/ansys/pymotorcad/assets/80680946/16511e95-19f8-43bf-a39b-785d8c633aeb)

This address split is potentially buggy and I believe is unnecessary, since in the end the request passed to `requests` is `address + "/jsonrpc"`. Moreover the gobal `SERVER_IP` will prevent to connect to multiple remote sessions and create unexpected bugs: in local we multiply sessions with many ports, but in a container environment we multiply sessions with many remote hosts.

I strongly suggest to make `url` a member of `MotorCADConnection` instead of just `port`, which solves both issues: in `_launch_motorcad_local()`, `url` would take the value `"http://localhost:" + port + "/jsonrpc"`, in `_launch_motorcad_remote()`, `url` would take the value `pim_instance.services["http"].uri + "/jsonrpc"`. I think that even outside of PIM, like a custom scenario where a user manages the launching themselves through a VM, docker-compose or anything, they can simply provide the URL themselves without bothering about the whole ip/port separation.

_Originally posted by @plule-ansys in https://github.com/ansys/pymotorcad/pull/62#discussion_r1210253758_

**Comment by SharadNair7** [comment]
Hello team,
I would like to contribute by making the suggested changes. Kindly assign this issue to me.

Regards

**Comment by jgsdavies** [comment]
> Hello team, I would like to contribute by making the suggested changes. Kindly assign this issue to me.
> 
> Regards

Hi,

I currently have a PR in review that is related. Can you check if this does what you want? https://github.com/ansys/pymotorcad/pull/125

Thanks
