### ISSUE TITLE
Re-add error handling to _get_graph

### ISSUE THREAD

**Issue by jgsdavies** [ansys/pymotorcad#139]
### 📝 Description of the feature

![image](https://github.com/ansys/pymotorcad/assets/80680946/7ca552c9-ef55-4154-870b-0b91f7dca904)

Can uncomment this error handling and check it works as expected.

@ravi-ansys Can you test with the script that originally found the bug?

**Comment by ravi-ansys** [comment]
Hi Jack, 
              I have tried to use get_magnetic_graph which will use _get_graph() function. 
I modified it as below 


        except MotorCADError as e:
            # break
            # Can't be used currently: Bug in Motor-CAD RPC server
            if "Point requested is greater than number of points available" in str(e):
              
                break
            else:
                raise

however i get below popup and only get the plot when i press okay. Should this happen ? i think the if else statement here should work and popup should not appear on my screen 


![pypmotorcad_graph](https://github.com/ansys/pymotorcad/assets/106396600/7a775780-cc63-457a-af47-c4c3d3d1425b)

**Comment by jgsdavies** [comment]
I think this is due to Motor-CAD messagedisplaystate. Usually this is set to not show these messages when scripting.

Might be worth setting this to 2 while we do _get_graph and then resetting to previous setting.

**Comment by ravi-ansys** [comment]
@jgsdavies 
 Hi, 
While setting the messagedisplaystate i am hitting the issue you mentioned in some other thread ("access to different method (set_variable" ) under rpc methods 
is there a way 
I tried this way which didn't work 

![Capture3](https://github.com/ansys/pymotorcad/assets/106396600/93d63d17-50be-47bd-b8bc-52386f725cf2)

**Comment by jgsdavies** [comment]
@ravi-ansys Sorry, didn't spot this before.

If you make```_get_graph``` a member of ```class _RpcMethodsGraphs``` then you can use ```self.set_variable("MessageDisplayState", 2)```

This works because ```_RpcMethodsGraphs``` is inherited by the main class.

If we are going to set MessageDisplayState then we need to make sure we revert back to the users original setting no matter what happens in our code. We can use a Try/Finally block to do this:
![image](https://github.com/ansys/pymotorcad/assets/80680946/7681c990-b600-4520-b764-34f77fc7cd1a)

**Comment by ravi-ansys** [comment]
@jgsdavies  I now placed the _get_graph under the _RPCMethodGraphs:
However i guess the following error saying we can't pass function as input arguments to _get_graph? 
![image](https://github.com/ansys/pymotorcad/assets/106396600/94a23c6a-058f-4265-b0ec-736c4167cfe9)
