### ISSUE TITLE
help on run_script method

### ISSUE THREAD

**Issue by gmalinve** [ansys/pymotorcad#192]
the run_script method should replace the RunScript native AEDT API, correct? so what should it do? open an AEDT and run a script?
Above all it doesn't allow the input file path to run. Could you help please?

Thanks!

**Comment by jgsdavies** [comment]
run_script should run the internal script in Motor-CAD:
![image](https://github.com/ansys/pymotorcad/assets/80680946/dbee9fe5-45f0-44ab-9087-d1cbd032a157)
