### ISSUE TITLE
Add corner rounding functions to Region() class

### ISSUE THREAD

**Issue by jgsdavies** [ansys/pymotorcad#248]
### 📝 Description of the feature

Create Region class methods to apply corner rounding.

![image](https://github.com/ansys/pymotorcad/assets/80680946/c3c00a23-91fb-455e-ab91-490eb914cf0f)

Ideally workflow would look something like this:

```python
region = mc.get_region("stator")

# Apply corner rounding to a specific point
# Raise exception if not possible
region.round_corner(int(region_point), float(radius))

# Apply corner rounding to whole region
# Raise exception if not possible
region.round_region(float(radius))

# Function to get max radius of a point
region.get_max_corner_radius(int(region_point))
```

### 💡 Steps for implementing the feature

Probably best to create the actual functionality in the ```EntityList``` class and then link to the new ```EntityList``` methods in ```Region```

Start with 2 lines for now. Is it possible/sensible to do line-arc or arc-arc corners?

**Comment by jgsdavies** [comment]
@james-packer Can you add any use cases that you would have for this.

**Comment by jmaravin** [comment]
I will be quite interested if this function gets implemented. 
thanks for your effort.
