### ISSUE TITLE
Add access to current .mot file name and if a file is loaded.

### ISSUE THREAD

**Issue by james-packer** [ansys/pymotorcad#251]
### 📝 Description of the feature

It would be useful to be able to access the 'Current Motor CAD File' name, and whether a file is currently loaded in Motor-CAD (i.e. if we are on the 'new' model, or if the user has saved or loaded a file. These are not currently visible as data store values, so can't be accessed through get_variable.

**Comment by jgsdavies** [comment]
Add new API methods for this
