### ISSUE TITLE
Make a function for adding lab custom losses

### ISSUE THREAD

**Issue by jgsdavies** [ansys/pymotorcad#336]
### 📝 Description of the feature

To add a custom loss in lab from scripting requires modifying array length variables and appending to arrays. Create 2 functions to make this easier e.g. 

![image](https://github.com/ansys/pymotorcad/assets/80680946/ce43c155-b39f-4d2a-b58f-8009e6cdb968)
![image](https://github.com/ansys/pymotorcad/assets/80680946/7ba264d0-188d-4b79-9c28-a551db6b66b6)

### 💡 Steps for implementing the feature

- implement for internal
- implement for external
- Functions should include add/remove/clear

Functions can live in src/ansys/motorcad/core/methods/rpc_methods_utility.py

**Comment by sarah-r-woodrow** [comment]
good first task for Shreya
